<?php
$lang['email_register'] = array('subject'=>'Registration Successful | AeroNet.io','body'=>'Welcome to AeroNet.io<br />Your registration is complete. <br />Please click on the link below or copy and paste it into your browser to login.<br /><br />[[URL]]');
$lang['email_reset'] = array('subject'=>'Request for Resetting Password','body'=>'<br />We have recieved a request to reset your password. <br />If you are the sender of this request then please click the following link to complete the request or copy the link below and past that in your browser.<br />However if you are not the person requesting the reset, please ignor this email.<br />Thank you,<br />AeroNet.io Support Team<br /><br /><a style="color:#000;font-weight:bold;" href="'.RIZ_HOST.site_url('auth/change').'?user=[[user_email]]'.'">'.RIZ_HOST.site_url('auth/change').'?user=[[user_email]]'.'</a>');
$lang['email_change'] = array('subject'=>'Password Reset Successfully','body'=>'Your password has been reset successfully and we hope that you don\'t forget it again. <br />Login to your account with following link.<br /><br /><a style="color:#000;font-weight:bold;" href="'.RIZ_HOST.site_url('auth\login').'">'.RIZ_HOST.site_url('auth\login').'</a>');
$lang['email_offer_created'] = array('subject'=>'Offer created successfully','body'=>'Hey [[USER_NAME]]<br /> You have successfully created a new offer. Now in the next step you will be recieving Return agreements against this Offer from which you will need to choose or or more agreements and start working on the Exchange Agreement you Choose.<br /><br />You can tack your offer from you Panel\'s Agreement section or just click on the following link you can see your created offer and agreements offered by other people.<br /><br /><a href="'.RIZ_HOST.'[[OFFE_URL]]">'.RIZ_HOST.'[[OFFE_URL]]</a><br /><br />You can also login to your account and Manage your agreement agains this offer or edit the details against this offer by visiting following link.<br /><br /><a href="'.RIZ_HOST.'[[OFFE_EDIT_URL]]">'.RIZ_HOST.'[[OFFE_EDIT_URL]]</a>');
$lang['email_proposal_submitted'] = array('subject'=>'A new Proposal has been submitted','body'=>'A new Proposal has been submitted on your offer<br /><br /><h4>[[OFFE_TITLE]]</h4><br /><label><b>Proposal Desciption</b></label><br />[[PROP_DESC]]<br /><br /><label><b>Duration for Completion</b></label><br />[[PROP_DUR]]<br /><br /><label><b>Exception Amount</b></label><br />[[PROP_AMOUNT]]');
$lang['email_proposal_edit'] = array('subject'=>'A Proposal has been edited','body'=>'A Proposal has been updated on your offer<br /><br /><h4>[[OFFE_TITLE]]</h4><br /><label><b>Proposal Desciption</b></label><br />[[PROP_DESC]]<br /><br /><label><b>Duration for Completion</b></label>[[PROP_DUR]]<br /><br /><label><b>Exception Amount</b></label><br />[[PROP_AMOUNT]]');
$lang['email_contact'] = array('subject'=>'A message from AeroNet.io','body'=>'A person has sent you a message with following details<br /><br />Name: [[NAME]]<br />Email: [[EMAIL]]<br />Phone: [[PHONE]]<br />Body: [[MSG]]');
$lang['email_proposal_rejected'] = array('subject'=>'Proposal rejected at AeroNet.io','body'=>'Your proposal for the Offer <a href="[[OFFE_URL]]">[[OFFE_TITLE]]</a> has been rejected by the Creator. The reason for rejection is as follow <br />[[REJ_REASON]]');
$lang['email_proposal_accepted'] = array('subject'=>'Proposal has been Accepted at AeroNet.io','body'=>'Congratulations <br />Your proposal for the Offer <a href="'.RIZ_HOST.'[[OFFE_URL]]">[[OFFE_TITLE]]</a> has been accepted by the Creator. The agreement for offer is as follow <br />[[AGREEMENT]]');
$lang['email_argument_filed'] = array('subject'=>'Argument has been reported against You','body'=>'Hi [[USER_NAME]]<br />An Argument has been filed against you by [[FUSER_NAME]] on the agreement which was submitted against the Offer <a href="[[OFFE_URL]]">[[OFFE_TITLE]]</a>. The dispute reason is as follow <br />[[DISP_REASON]]');
$lang['email_offer_invited'] = array('subject'=>'Invitation for Proposal Submission','body'=>'Hello [user_name]<br /> You are invited to submit a proposal on offer <a href="[[OFFE_URL]]">[[OFFE_TITLE]]</a><br />So feel free to login to your account submit a proposal on <a href="[[OFFE_URL]]">[[OFFE_URL]]</a>');
$lang['email_comment_posted'] = array('subject'=>'Your Comment was Successfully Posted','body'=>'Hello [[user_name]]<br />Your following comment has been successfully posted on <a href="'.RIZ_HOST.'[[post_url]]">[[post]]</a><br /><br />"[[comment]]"');
$lang['email_agreement'] = array('subject'=>'Agreement created successfully','body'=>'Hello [[USER_NAME]]<br />Agreement has been successfully created. Please visit you Agreement board by clicking the following link <a href="'.RIZ_HOST.'[[AGREE_URL]]">[[AGREE_URL]]</a><br /><br />');
$lang['email_feed_back'] = array('subject'=>'Feedback Submitted','body'=>'Hello [[USER_NAME]]<br />A feedback has been submitted by [[FUSER_NAME]] againt your agreement <a href="'.RIZ_HOST.'[[AGREE_URL]]">[[OFFER_TITLE]]</a><br /><br />Rating:<b>[[RATE]]/5<br /><br />Comment:<br />[[MSG]]');
$lang['email_feed_back_submitter'] = array('subject'=>'Feedback Submission Successful','body'=>'Hello [[USER_NAME]]<br />You feedback for [[FUSER_NAME]] againt the agreement <a href="'.RIZ_HOST.'[[AGREE_URL]]">[[OFFER_TITLE]]</a> has been submitted successfully. Following are the details of the submission.<br /><br />Rating:<b>[[RATE]]/5<br /><br />Comment:<br />[[MSG]]');
$lang['email_postcard_confirmation'] = array('subject'=>'Postcard sending details','body'=>'Hello [[USER_NAME]]<br />We are going to send you post cards to following recipients<br /><br />[[POSTCARD_PLAINS]] Thanks');
$lang['email_postcard_details'] = array('subject'=>'Request for Postcard Delivery','body'=>'Hi Admin, <br />User with following details have submitted a request for sending Postcard. <h3>User Details</h3><br /> <b>Name: </b>[[UNAME]]<br /> <b>Eamil: </b>[[UEMAIL]]<br /> <b>Address: </b>[[UADD]]<br /> <b>Tele: </b>[[UTele]]<br /><br /><br /><h3>Aircraft Details</h3><br />[[POSTCARD_PLAINS]] <br />Thanks');
$lang['email_send_quote'] = array('subject'=>'Quotation from '.RIZ_SITE_NAME,'body'=>'[[USER_NAME]]<br />Following is the Quote against your request<br />[[QUOTE]]<br /><br /> Thanks');
$lang['email_job_application'] = array('subject'=>'Application for Job','body'=>'Hello [[USER_NAME]], <br /> An applicant with following details has submitted an application against the job [[JOB_TITLE]]<br /><table><tr><th>Name</th><td>[[APP_NAME]]</td></tr><tr><th>Email</th><td>[[APP_EMAIL]]</td></tr><tr><th>Subject</th><td>[[APP_SUBJECT]]</td><tr><th>Message</th><td>[[APP_MESSAGE]]</td></tr></table><br /><br /><h2>Resume</h2>[[RESUME]]');
$lang['email_job_post'] = array('subject'=>'Job Posted','body'=>'Hello, <br /> A Job with following details has submitted [[JOB_TITLE]]<br /><table><tr><th>Name</th><td>[[USER_NAME]]</td></tr><tr><th>Job</th><td>[[JOB_LINK]]</td></tr></table><br /><br />');

$lang['email_job_application_thanks'] = array('subject'=>'Thanks for your application','body'=>'Hello [[USER_NAME]]<br />Thanks for you submitting your application. Your detailed message with resume has been forwarded to the Job Owner and Admin they will be back with you shortly');
$lang['email_purchase_order'] = array('subject'=>'Order submitted sucessfully','body'=>'Hello [[USER_NAME]]<br />Thanks for purchasing from AeroNet.io. We will contact you within 48 hours. Following are the details of your order [[ORDER]]');
$lang['email_application_status'] = array('subject'=>'Qutation Reply at '.RIZ_SITE_NAME,'body'=>'Hello [[USER_NAME]]<br />Your quotation posted at <a href="'.RIZ_HOST.'[[JOB_URL]]">[[JOB_TITLE]]</a> has been [[STATUS]] by owner.');

$lang['email_verification'] = array('subject'=>'Pilot verification from AeroNet.io','body'=>'A pilot was unable to verify via medical date please use following links to check his identity and update his status<br /><br /><a href="'.RIZ_ADMIN_URL.'edit/piolet/[[ID]].html">'.RIZ_ADMIN_URL.'pilot/[[ID]]</a>');

$lang['email_invitation'] = array('subject'=>'Connection Request from '.RIZ_SITE_NAME,'body'=>'Hello [[USER_NAME]], [[SENDER_NAME]] has sent you a firend request. Click the link below to accept it <br /><br /><a href="'.RIZ_ADMIN_URL.'account/accept/[[ID]].html">'.RIZ_ADMIN_URL.'pilot/[[ID]]</a>');

$lang['email_register_invitation'] = array('subject'=>'Connection Request from '.RIZ_SITE_NAME,'body'=>'Hello [[USER_NAME]], [[SENDER_NAME]] has invited you to join '.RIZ_SITE_NAME.'. Click the link below to and signup today <br /><br /><a href="'.RIZ_FULL_URL.'register">'.RIZ_FULL_URL.'register</a>');


$lang['follow_invitation'] = array('subject'=>'A new follower at AeroNet.io','body'=>'Hello [[UNAME]]<br />A new pilot is following the department. You can visit his profile at <a href="[[USER_URL]]">[[USER_TITLE]]</a>');
$lang['connection_invitation'] = array('subject'=>'A connection request from AeroNet.io','body'=>'Hello [[UNAME]]<br />A new pilot is following the department. Pleaes login to accept the invitation from <a href="[[USER_URL]]">[[USER_TITLE]]</a>');

?>
